default:
  tags:
   - rancher2

stages:
  - create_build_image
  - create_target_image_content
  - create_target_image

create_build_image:
  only:
   - /^build-[0-9]+\.[0-9]+\.[0-9]+/
  stage: create_build_image 
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["/busybox/sh"]
  script:
    - if [ -z "$ACR_PROJECT" ]; then export ACR_NAME="$ACR_REGISTRY/$JANUS_BUILD_IMAGE"; else export ACR_NAME="$ACR_REGISTRY/$ACR_PROJECT/$JANUS_BUILD_IMAGE"; fi
    - if [ -z "$NCR_PROJECT" ]; then export NCR_NAME="$NCR_REGISTRY/$JANUS_BUILD_IMAGE"; else export NCR_NAME="$NCR_REGISTRY/$NCR_PROJECT/$JANUS_BUILD_IMAGE"; fi
    - echo "{\"auths\":{\"$ACR_REGISTRY\":{\"auth\":\"$ACR_AUTH\"},\"$NCR_REGISTRY\":{\"auth\":\"$NCR_AUTH\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --build-arg IMAGE_TOOL=external --context . --dockerfile Dockerfile.build 
        --destination $ACR_NAME:$CI_COMMIT_TAG
        --destination $ACR_NAME:latest
        --destination $NCR_NAME:$CI_COMMIT_TAG
        --destination $NCR_NAME:latest

create_target_image_content:
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+/
  stage: create_target_image_content
  image:
    name: ncr.nuance.com/ewebrtc-docker-dev/janus_build:latest
    entrypoint: ["/bin/bash"]
  artifacts:
    paths:
      - image/
    expire_in: 1 hour
  script:
    - export IMAGE_TOOL=external
    - cd /image
    - ./build.sh
    - mv /image $CI_PROJECT_DIR

create_target_image:
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+/
  stage: create_target_image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["/busybox/sh"]
  script:
    - if [ -z "$ACR_PROJECT" ]; then export ACR_NAME="$ACR_REGISTRY/$JANUS_TARGET_IMAGE"; else export ACR_NAME="$ACR_REGISTRY/$ACR_PROJECT/$JANUS_TARGET_IMAGE"; fi
    - if [ -z "$NCR_PROJECT" ]; then export NCR_NAME="$NCR_REGISTRY/$JANUS_TARGET_IMAGE"; else export NCR_NAME="$NCR_REGISTRY/$NCR_PROJECT/$JANUS_TARGET_IMAGE"; fi
    - echo "{\"auths\":{\"$ACR_REGISTRY\":{\"auth\":\"$ACR_AUTH\"},\"$NCR_REGISTRY\":{\"auth\":\"$NCR_AUTH\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context ./image --dockerfile Dockerfile.exec 
        --destination $ACR_NAME:$CI_COMMIT_TAG 
        --destination $ACR_NAME:latest
        --destination $NCR_NAME:$CI_COMMIT_TAG
        --destination $NCR_NAME:latest

  
    