default:
  tags:
   - rancher2

stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$ACR_REGISTRY\":{\"username\":\"$ACR_USER\",\"password\":\"$ACR_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --build-arg IMAGE_TOOL=$IMAGE_TOOL --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.build --destination $CI_REGISTRY_IMAGE:latest
