default:
  tags:
   - rancher2

stages:
  - build

publish_to_acr:
  only:
   - master
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["/busybox/sh"]
  script:
    - echo "{\"auths\":{\"$ACR_REGISTRY\":{\"username\":\"$ACR_USER\",\"password\":\"$ACR_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --build-arg IMAGE_TOOL=external --context . --dockerfile Dockerfile.build --destination acrwebrtc.azurecr.io/janus_build:latest
