default:
  tags:
   - rancher2

stages:
  - create_build_image
  - create_target_image_content
  - create_target_image

create_build_image:
  only:
   - master
   - tags
  stage: create_build_image 
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["/busybox/sh"]
  before_script:
    - if [ -z $CI_COMMIT_TAG ]; then CI_COMMIT_TAG=latest; fi
  script:
    - echo "{\"auths\":{\"$ACR_REGISTRY\":{\"username\":\"$ACR_USER\",\"password\":\"$ACR_PASSWORD\"},\"$NCR_REGISTRY\":{\"username\":\"$NCR_USER\",\"password\":\"$NCR_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --build-arg IMAGE_TOOL=external --context . --dockerfile Dockerfile.build 
        --destination $ACR_REGISTRY/$JANUS_BUILD_IMAGE:$CI_COMMIT_TAG 
        --destination $ACR_REGISTRY/$JANUS_BUILD_IMAGE:latest
        --destination $NCR_REGISTRY/$JANUS_BUILD_IMAGE:$CI_COMMIT_TAG 
        --destination $NCR_REGISTRY/$JANUS_BUILD_IMAGE:latest

create_target_image_content:
  only:
#    - master
    - tags
  stage: create_target_image_content
  image:
    name: acrwebrtc.azurecr.io/janus_build:latest
    entrypoint: ["/bin/bash"]
  before_script:
    - IMAGE_TOOL=external
  artifacts:
    paths:
      - /image
    expire_in: 1 hour
  script:
    - cd /image
    - ./build.sh
  
create_target_image:
  only:
#    - master
    - tags
  stage: create_target_image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["/busybox/sh"]
  script:
    - echo "{\"auths\":{\"$ACR_REGISTRY\":{\"username\":\"$ACR_USER\",\"password\":\"$ACR_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context /image --dockerfile Dockerfile.exec 
        --destination $ACR_REGISTRY/$JANUS_IMAGE:$CI_COMMIT_TAG 
        --destination $ACR_REGISTRY/$JANUS_IMAGE:latest

  
    