# Docker file for creating a Janus build image.
# Trigger the image build by issuing:
# docker build -t <buld image name> -f Dockerfile.build .

FROM ubuntu:18.04

# Add the build script
ADD scripts/build.sh /

# First we need to add all the tools and components
RUN scripts/setup.sh

