# Docker file for creating a Janus gateway build image.

FROM ubuntu:18.04

# Add the scripts
ADD scripts/setup.sh scripts/build.sh scripts/start.sh Dockerfile.exec /image/

# Add janus configuration
ADD janus_config /image/janus_config

# First we need to add all the tools and components
RUN image/setup.sh

# Commented out for convenience
ENTRYPOINT /image/build.sh